version: '3.8'
services:
  freeswitch:
    build:
      context: .
      args:
        TOKEN: "pat_yC9hf9cTipf8XTiGnNRrXn9V"
    volumes:
      - ./configuration:/etc/freeswitch
      - ./tmp:/tmp
    network_mode: host
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5080:5080/tcp"
      - "5080:5080/udp"
      - "5061:5061/tcp"
      - "5081:5081/tcp"
      - "5066:5066/tcp"
      - "7443:7443/tcp"
      - "8021:8021/tcp"
      - "16384-32768:16384-32768/udp"
      - "64535-65535:64535-65535/udp"
